version: '3'

services:
  db:
    image: neo4j
    restart: always
    volumes:
      - ./db/data:/data
      - ./db/logs:/logs
      - ./db/import:/var/lib/neo4j/import
      - ./db/plugins:/plugins
      - ./db/conf:/conf
      - ./deploy:/deploy
    ports:
      - '7474:7474'
      - '7687:7687'
    expose:
      - '7474'
      - '7687'
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASS}"

  server:
    build:
      context: ./deploy/app
    depends_on:
      - db
    restart: always
    volumes:
      - ./app:/app
      - ./deploy:/deploy

